---
- debug:
    msg: "Waiting for cluster to finish provisioning."


- name: check cluster
  azure_rm_openshiftmanagedcluster_info:
    resource_group: "{{ azr_resource_group }}"
    name: "{{ azr_aro_cluster }}"
  register: _aro_check
  until: (_aro_check.clusters.properties.provisioningState == "Succeeded")
  failed_when: _aro_check.clusters.properties.provisioningState == "Failed"
  retries: 120
  delay: 60

- fail:
    msg: "Cluster {{ azr_aro_cluster }} failed to provision."
  when: _aro_check.clusters.properties.provisioningState == "Failed"

- set_fact:
    _cluster_ready: True
