---
- hosts:      "all"
  connection: "local"
  vars_files:
      - vars/main.yaml

  roles:
    - name: roles/cluster-delete
    - name: roles/infra-delete
    #   when:
    #     - (rosa_private or rosa_private_link) or
    #       (enable_jumphost | default(False) | bool)
    # - name: roles/vpc-delete
    #   when: rosa_subnet_ids | default([]) | length == 0



